### PR TITLE
Unix style line endings by default

### PR DESCRIPTION
**Pull request by benknox**
Change default line endings to Unix style. That way files being written with content formatted by this utility will be compatible with GIT (windows style line endings make any change to a file appears as an entire file replacement to the git diff)

### CODE REVIEW

**Comment by bdw429s** [comment]
Hi @benknox !  Thanks for sending the pull over here.  So, I have my Git settings set up so I always get windows line endings when I checkout a repo and then it auto-converts back to Unix when I commit/push.  Do you think it would be best to default to whatever OS is in use and then the Git client can auto-convert back as necessary.  I'm a little afraid that if we go to unix all the time, older programs like Window Notepad will stop showing the line breaks all together.

Lucee has a helpful variable in the server scope that shows you the OS-specific line ending, otherwise, we can look at a couple java system properties to determine Mac, Linux, Windows.  Thoughts?

**Comment by jcberquist** [comment]
Hi all, what is the status of this pull request? I would really like to see this pushed forward as I do find it annoying that when using a Mac I still get the `server.json` files written to disk with Windows newlines. I think it could be as simple as checking `os.name` for the presence of "windows" and only using Windows line endings in that case, since both Unix and OSX default to just the line feed character.

Also, @bdw429s, I think cfconfig doesn't currently depend on this module to pretty print JSON, and it also always writes CRLF; I would love to see that updated as well.

**Comment by bdw429s** [comment]
Looks like this pull got forgotten about.  I was waiting for it to be updated to use the line endings that are appropriate for the local file system.  Detecting the OS is very easy and you can see an example of it here:

https://github.com/Ortus-Solutions/commandbox/blob/development/src/cfml/system/util/FileSystem.cfc#L166-L168

I'm surprised CFConfig isn't using it.  I had originally pasted in an early version of the pretty print function back before I turned it into a module and I apparently forgot to go back and swap it out for the module.  I also intended to turn the getInheritedMetadata() function into a module as well since it's self contained and very handy.  I extracted it from the ColdBox core.

https://github.com/Ortus-Solutions/cfconfig/blob/master/models/Util.cfc

**Comment by bdw429s** [comment]
Since it looks like Ben isn't around anymore I'll just merge this and finish fixing it so it doesn't keep sitting here.

**Comment by jcberquist** [comment]
Thanks Brad! I appreciate it. 

This is a bit off topic, but bumping into this again led me to try to create a JSON parser / printer combo for the sole purpose of being able to sort the keys in a JSON object - it actually seems to work reasonably well and compares favorably with regards to performance to the implementation here, at least until the JSON file size gets very large. Is that something that could be contributed to this module? 

I certainly understand if you don't want this module to get more complex (or simply don't have the time), and I am not sure how you would merge what you currently have with what I came up with. But I thought I would at least ask 😄 . If you are interested I am happy to share what I have with you so you can take a look at it first.

**Comment by bdw429s** [comment]
I modified JSON Pretty print to default the newline char based on the OS (and shaved a yak while I was in there).  Then I updated CommandBox to use the latest version of JSON Pretty print.  This will be built on the bleeding edge in a few minutes.  Please help test this to confirm it is fixed.

@jcberquist Your lib sounds pretty cool.  Since I've named tis project pretty narrowly, I think the best thing would probably be for you to just published a new module for what you have.  Your module could depend on this one if it wanted, or people could mix and match them both.

**Comment by bdw429s** [comment]
CFConfig has been updated to use this module for JSON pretty print so it should have the same default behavior as well.

**Comment by jcberquist** [comment]
Nice Brad, thank you so much. 

If I create my own library for JSON formatting, would it be possible to configure CommandBox to prefer it over the default JSONPrettyPrint and inject it instead?

**Comment by bdw429s** [comment]
In theory yes if you overwrite the WireBox mapping of `JSONPrettyPrint` after the CLI has started.  All of the internal use in CommandBox funnels through the legacy `Formatter.formatJSON()` which references the lib through an injected provider.  

For what it's worth, CFConfig injects it as `JSONPrettyPrint@JSONPrettyPrint` but doesn't use a WireBox provider so it would probably be too late but it would be possible to refactor CFConfig to ask WireBox for the mapping every time.

**Comment by jcberquist** [comment]
Thanks Brad for all of your time. I am not so worried about CFConfig any more since you updated it earlier this year to use ordered structs, so the JSON keys are already sorted. I will play around with CommandBox and see what I can do.

**Comment by jcberquist** [comment]
Hey @bdw429s sorry to revive this one more time, but I wasn't sure where the best place was to put this question. I finally got my alternate JSON formatter up here: <https://github.com/jcberquist/jsonformat>. I haven't put in on ForgeBox yet - I wanted to confirm that you would prefer to keep it separate from JSONPrettyPrint since the only real difference is that my library adds the ability to sort JSON object keys when formatting.

Assuming I proceed with it as a separate module, I was able to hack out a CommandBox extension that depends on my JSON module, and simply does a `binder.map('JSONPrettyPrint').toValue(myFormatter)` in an `onCLIStart()` interceptor. This works (i.e. core CommandBox JSON formatting is then run through my module), but I was hoping you could tell me if there is a better way to override the default WireBox mapping. (I just tried things till this worked 😁).

**Comment by bdw429s** [comment]
Hi @jcberquist if your module does the exact same thing but with a single optional addition then I'm not against looking at merging it over.  I'd say two things probably need to be tested:

* The unit tests in the repo still pass and if we drop it in, it won't create any whitespace changes in people's `box.json` or `server.json` files out of the box after they upgrade.
* It needs to be tested with large JSON files.  I've had to do a lot of work over the years to keep the default JSON formatter nice and fast-- especially using Stringbuilder classes and not doing any concatenation if possible.  My `~/.CommandBox/servers.json` file is 1.5 Megs right now but I've had it get several times larger than that before when I have dozens of test servers locally.   

Regarding your question of overriding the mapping, what you have is pretty much it.  I wouldn't use the `toValue()` bit bur rather just `map().to()` and let WireBox create the instance of the CFC for you.

**Comment by jcberquist** [comment]
Hey @bdw429s - wow! I don't think I have ever gotton my `servers.json` near 1.5MB, let alone several times larger; I am impressed. So I have created a test `servers.json` file by taking mine and cloning one of the servers in it until I got the file size to about 1.5MB - I then tested with the following simple script:
```cfc
prettyprint = new JSONPrettyPrint();
printer = new JsonPrinter();

json = deserializeJSON( fileRead( expandPath( '/json/servers-test.json' ) ) );
times = 10;

start = getTickCount();
for ( i = 1; i <= times; i++ ) {
    formatted = prettyprint.formatJson( json );
}
writeOutput( '#( getTickCount() - start ) / times#ms<br>' );

start = getTickCount();
for ( i = 1; i <= times; i++ ) {
    formatted = printer.formatJson( json );
}
writeOutput( '#( getTickCount() - start ) / times#ms<br>' );
```
On my machine, JSONPrettyPrint takes about 1060ms on average to format the 1.5MB json file. Whereas it takes the JsonPrinter about 450ms on average to format the same file. So I don't think performance will be an issue.

I can also confirm that it passes all of the JSONPrettyPrint tests simply by dropping it (and `JSONSimpleParser.cfc`) in in place of `JSONPrettyPrint.cfc`.  They also produce the exact same output by default when run over my `server.json` file.  I can try to test on more files.

I did however find a bug in my parser which is now fixed 😄 .

**Comment by bdw429s** [comment]
@jcberquist Cool, well let's give it a shot.  Send a pull to the https://github.com/Ortus-Solutions/JSONPrettyPrint repo with the updated implementation.  Once it's in there, we can pull the new version into CommandBox.  The way I update the core modules like that is literally to CD into the cfml/system folder and run `update`, then I just commit the changes.  

So, on this note-- I'm curious how I can go about updating CommandBox so existing JSON files are left as is to prevent annoying rearranging of JSON but new JSON files could be created with sorted keys for consistency.  If a file was already sorted, it would be cool for any new keys to be added in the correct place but I'm not really sure how to detect that.  I'm also thinking it could be handy to have a basic JSON command that could normalize any JSON file just for the point of cleaning it up.  Hmm, CommandBox could even have a setting to force normalization of JSON keys.  Lots of options.

**Comment by jcberquist** [comment]
Sounds great, I will get a pull request together. 

Since the sorting of keys is off by default to preserve the current behavior of JSONPrettyPrint, I had been envisioning adding some configuration settings to CommandBox to specify how to format JSON that the formatterUtil could read and pass to JSONPrettyPrint.

I do think it would be possible to use `JSONSimpleParser.cfc` directly to check if the topmost object keys in a JSON string are sorted or not, but then you would have to keep track of that information until it was time to write the file back out (or do an additional read and check of the file before writing it out).

Having a command that normalizes JSON files sounds great to me, particularly normalizing keys. I wonder if JSON schema files (once they are created) could be used for that purpose.

**Pull request merged**
